version: '3'

services:
  krakend_sample:
    container_name: krakend_sample
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/etc/krakend